### ISSUE TITLE
Blank screen on back press from dashboard

### ISSUE THREAD

**Issue by sayansil** [sayansil/Pandu#1]
Screenshots attached [here](https://i.ibb.co/b7GpgPk/Screenshot-from-2020-05-08-23-15-05.png).

**Comment by mellophi** [comment]
> Screenshots attached [here](https://i.ibb.co/b7GpgPk/Screenshot-from-2020-05-08-23-15-05.png).

**Comment by mellophi** [comment]
Thanks for opening the issue. The bug has been fixed in the latest patches.
